//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reception.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reception.Resources.LocalizedRes", typeof(LocalizedRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;XtraSerializer version=&quot;1.0&quot; application=&quot;View&quot;&gt;
        ///  &lt;property name=&quot;#LayoutVersion&quot; /&gt;
        ///  &lt;property name=&quot;VertScrollTipFieldName&quot; /&gt;
        ///  &lt;property name=&quot;PreviewFieldName&quot; /&gt;
        ///  &lt;property name=&quot;GroupPanelText&quot; /&gt;
        ///  &lt;property name=&quot;NewItemRowText&quot; /&gt;
        ///  &lt;property name=&quot;LevelIndent&quot;&gt;-1&lt;/property&gt;
        ///  &lt;property name=&quot;PreviewIndent&quot;&gt;-1&lt;/property&gt;
        ///  &lt;property name=&quot;PreviewLineCount&quot;&gt;-1&lt;/property&gt;
        ///  &lt;property name=&quot;ScrollStyle&quot;&gt;LiveVertScroll, LiveHorzScroll&lt;/property&gt;
        ///  &lt;property name=&quot;FocusRectStyle&quot;&gt;CellFocu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string grd_PatientsList {
            get {
                return ResourceManager.GetString("grd_PatientsList", resourceCulture);
            }
        }
    }
}
