//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountingJournalTransaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccountingJournalTransaction()
        {
            this.AccountingJournalEntryTransactions = new HashSet<AccountingJournalEntryTransaction>();
            this.CashBoxInOutTransaction_AccountingJournalTransaction = new HashSet<CashBoxInOutTransaction_AccountingJournalTransaction>();
            this.CustomerPaymentTransactions = new HashSet<CustomerPaymentTransaction>();
        }
    
        public int ID { get; set; }
        public string JounralSerial { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public double TransactionAmount { get; set; }
        public bool IsOnDuty { get; set; }
        public Nullable<int> FinancialTransactionType_P_ID { get; set; }
        public string Description { get; set; }
        public Nullable<int> InsertedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountingJournalEntryTransaction> AccountingJournalEntryTransactions { get; set; }
        public virtual FinancialTransactionType_p FinancialTransactionType_p { get; set; }
        public virtual User_cu User_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashBoxInOutTransaction_AccountingJournalTransaction> CashBoxInOutTransaction_AccountingJournalTransaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerPaymentTransaction> CustomerPaymentTransactions { get; set; }
    }
}
