//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountingJournalEntryTransaction
    {
        public int ID { get; set; }
        public string Serial { get; set; }
        public int AccountingJournalTransaction_ID { get; set; }
        public int ChartOfAccount_CU_ID { get; set; }
        public double Amount { get; set; }
        public bool IsDebit { get; set; }
        public bool IsOnDuty { get; set; }
        public string Description { get; set; }
        public int InsertedBy { get; set; }
    
        public virtual AccountingJournalTransaction AccountingJournalTransaction { get; set; }
        public virtual ChartOfAccount_cu ChartOfAccount_cu { get; set; }
        public virtual User_cu User_cu { get; set; }
    }
}
