//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashBoxTransactionType_p
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CashBoxTransactionType_p()
        {
            this.CashBoxInOutTransactions = new HashSet<CashBoxInOutTransaction>();
            this.CashBoxTransactionType_GeneralChartOfAccountType_cu = new HashSet<CashBoxTransactionType_GeneralChartOfAccountType_cu>();
            this.CashBoxTransactionType_GeneralChartOfAccountType_p = new HashSet<CashBoxTransactionType_GeneralChartOfAccountType_p>();
        }
    
        public int ID { get; set; }
        public string Name_P { get; set; }
        public string Name_S { get; set; }
        public string Description { get; set; }
        public int MultiplierEffect { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashBoxInOutTransaction> CashBoxInOutTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashBoxTransactionType_GeneralChartOfAccountType_cu> CashBoxTransactionType_GeneralChartOfAccountType_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashBoxTransactionType_GeneralChartOfAccountType_p> CashBoxTransactionType_GeneralChartOfAccountType_p { get; set; }
    }
}
