//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashBoxInOutTransaction_AccountingJournalTransaction
    {
        public int ID { get; set; }
        public int CashBoxInOutTransactionID { get; set; }
        public int AccountingJournalTransactionID { get; set; }
        public bool IsOnDuty { get; set; }
        public int InsertedBy { get; set; }
    
        public virtual AccountingJournalTransaction AccountingJournalTransaction { get; set; }
        public virtual CashBoxInOutTransaction CashBoxInOutTransaction { get; set; }
        public virtual User_cu User_cu { get; set; }
    }
}
