//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashBoxTransactionType_GeneralChartOfAccountType_cu
    {
        public int ID { get; set; }
        public int CashBoxTransactionType_P_ID { get; set; }
        public int GeneralChartOfAccountType_CU_ID { get; set; }
        public bool IsOnDuty { get; set; }
        public int InsertedBy { get; set; }
    
        public virtual CashBoxTransactionType_p CashBoxTransactionType_p { get; set; }
        public virtual GeneralChartOfAccountType_cu GeneralChartOfAccountType_cu { get; set; }
        public virtual User_cu User_cu { get; set; }
    }
}
