//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChartOfAccount_cu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChartOfAccount_cu()
        {
            this.AccountingJournalEntryTransactions = new HashSet<AccountingJournalEntryTransaction>();
            this.Bank_cu = new HashSet<Bank_cu>();
            this.BankAccount_cu = new HashSet<BankAccount_cu>();
            this.CashBox_cu = new HashSet<CashBox_cu>();
            this.CashBoxInOutTransactions = new HashSet<CashBoxInOutTransaction>();
            this.ChartOfAccount_cu1 = new HashSet<ChartOfAccount_cu>();
            this.ChartOfAccount_FinancialStatementElement_cu = new HashSet<ChartOfAccount_FinancialStatementElement_cu>();
            this.ChartOfAccount_GeneralChartOfAccountType_cu = new HashSet<ChartOfAccount_GeneralChartOfAccountType_cu>();
            this.TrialBalanceTransactions = new HashSet<TrialBalanceTransaction>();
            this.ChartOfAccountBalances = new HashSet<ChartOfAccountBalance>();
            this.InsuranceCarrier_cu = new HashSet<InsuranceCarrier_cu>();
            this.InventoryHousing_cu = new HashSet<InventoryHousing_cu>();
            this.InventoryItem_cu = new HashSet<InventoryItem_cu>();
            this.InventoryItemBrand_cu = new HashSet<InventoryItemBrand_cu>();
            this.InventoryItemCategory_cu = new HashSet<InventoryItemCategory_cu>();
            this.InventoryItemGroup_cu = new HashSet<InventoryItemGroup_cu>();
            this.Person_ChartOfAccount_cu = new HashSet<Person_ChartOfAccount_cu>();
            this.PersonType_ChartOfAccount_cu = new HashSet<PersonType_ChartOfAccount_cu>();
            this.Service_ChartOfAccount_cu = new HashSet<Service_ChartOfAccount_cu>();
            this.Service_cu = new HashSet<Service_cu>();
            this.ServiceCategory_cu = new HashSet<ServiceCategory_cu>();
            this.ServiceType_ChartOfAccount_cu = new HashSet<ServiceType_ChartOfAccount_cu>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ParentChartOfAccount_CU_ID { get; set; }
        public string Name_P { get; set; }
        public string Name_S { get; set; }
        public long Serial { get; set; }
        public int ChartOfAccountCodeMargin_P_ID { get; set; }
        public bool IsDebit { get; set; }
        public bool IsOnDuty { get; set; }
        public string Description { get; set; }
        public Nullable<int> InsertedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountingJournalEntryTransaction> AccountingJournalEntryTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bank_cu> Bank_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BankAccount_cu> BankAccount_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashBox_cu> CashBox_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashBoxInOutTransaction> CashBoxInOutTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChartOfAccount_cu> ChartOfAccount_cu1 { get; set; }
        public virtual ChartOfAccount_cu ChartOfAccount_cu2 { get; set; }
        public virtual ChartOfAccountCodeMargin_p ChartOfAccountCodeMargin_p { get; set; }
        public virtual User_cu User_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChartOfAccount_FinancialStatementElement_cu> ChartOfAccount_FinancialStatementElement_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChartOfAccount_GeneralChartOfAccountType_cu> ChartOfAccount_GeneralChartOfAccountType_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrialBalanceTransaction> TrialBalanceTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChartOfAccountBalance> ChartOfAccountBalances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsuranceCarrier_cu> InsuranceCarrier_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryHousing_cu> InventoryHousing_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryItem_cu> InventoryItem_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryItemBrand_cu> InventoryItemBrand_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryItemCategory_cu> InventoryItemCategory_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryItemGroup_cu> InventoryItemGroup_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person_ChartOfAccount_cu> Person_ChartOfAccount_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonType_ChartOfAccount_cu> PersonType_ChartOfAccount_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service_ChartOfAccount_cu> Service_ChartOfAccount_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service_cu> Service_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceCategory_cu> ServiceCategory_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceType_ChartOfAccount_cu> ServiceType_ChartOfAccount_cu { get; set; }
    }
}
