//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerPaymentTransaction
    {
        public int ID { get; set; }
        public Nullable<int> Customer_CU_ID { get; set; }
        public Nullable<int> FinanceInvoiceID { get; set; }
        public Nullable<double> TotalRequired { get; set; }
        public Nullable<double> TotalPayment { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> IsPaymentEnough { get; set; }
        public Nullable<int> AccountingJournalTransactionID { get; set; }
        public Nullable<int> InsertedBy { get; set; }
        public Nullable<bool> IsOnDuty { get; set; }
    
        public virtual AccountingJournalTransaction AccountingJournalTransaction { get; set; }
        public virtual Customer_cu Customer_cu { get; set; }
        public virtual FinanceInvoice FinanceInvoice { get; set; }
        public virtual User_cu User_cu { get; set; }
    }
}
