//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department_JobTitle_cu
    {
        public int ID { get; set; }
        public int Department_CU_ID { get; set; }
        public int JobTitle_CU_ID { get; set; }
        public Nullable<int> InsertedBy { get; set; }
    
        public virtual Department_cu Department_cu { get; set; }
        public virtual JobTitle_cu JobTitle_cu { get; set; }
        public virtual User_cu User_cu { get; set; }
    }
}
