//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnosis_cu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Diagnosis_cu()
        {
            this.Diagnosis_cu1 = new HashSet<Diagnosis_cu>();
            this.DiagnosisCategory_Diagnosis_cu = new HashSet<DiagnosisCategory_Diagnosis_cu>();
            this.Doctor_Diagnosis_cu = new HashSet<Doctor_Diagnosis_cu>();
            this.VisitTiming_Diagnosis = new HashSet<VisitTiming_Diagnosis>();
        }
    
        public int ID { get; set; }
        public string Name_P { get; set; }
        public string Name_S { get; set; }
        public Nullable<int> ParentDiagnosis_CU_ID { get; set; }
        public bool IsDoctorRelated { get; set; }
        public string Description { get; set; }
        public string Abbreviation { get; set; }
        public bool IsOnDuty { get; set; }
        public Nullable<int> InsertedBy { get; set; }
        public bool IsMerkInsertion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Diagnosis_cu> Diagnosis_cu1 { get; set; }
        public virtual Diagnosis_cu Diagnosis_cu2 { get; set; }
        public virtual User_cu User_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiagnosisCategory_Diagnosis_cu> DiagnosisCategory_Diagnosis_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doctor_Diagnosis_cu> Doctor_Diagnosis_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitTiming_Diagnosis> VisitTiming_Diagnosis { get; set; }
    }
}
