//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiagnosisCategory_cu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DiagnosisCategory_cu()
        {
            this.DiagnosisCategory_cu1 = new HashSet<DiagnosisCategory_cu>();
            this.DiagnosisCategory_Diagnosis_cu = new HashSet<DiagnosisCategory_Diagnosis_cu>();
            this.Doctor_DiagnosisCategory_cu = new HashSet<Doctor_DiagnosisCategory_cu>();
        }
    
        public int ID { get; set; }
        public string Name_P { get; set; }
        public string Name_S { get; set; }
        public Nullable<int> ParentDiagnosisCategory_CU_ID { get; set; }
        public bool IsDoctorRelated { get; set; }
        public string Abbreviation { get; set; }
        public bool IsOnDuty { get; set; }
        public Nullable<int> InsertedBy { get; set; }
        public bool IsMerkInsertion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiagnosisCategory_cu> DiagnosisCategory_cu1 { get; set; }
        public virtual DiagnosisCategory_cu DiagnosisCategory_cu2 { get; set; }
        public virtual User_cu User_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiagnosisCategory_Diagnosis_cu> DiagnosisCategory_Diagnosis_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doctor_DiagnosisCategory_cu> Doctor_DiagnosisCategory_cu { get; set; }
    }
}
