//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor_Service_cu
    {
        public int ID { get; set; }
        public int Doctor_CU_ID { get; set; }
        public Nullable<int> DoctorCategory_CU_ID { get; set; }
        public Nullable<int> Service_CU_ID { get; set; }
        public Nullable<int> ServiceCartegory_CU_ID { get; set; }
        public Nullable<int> ServiceType_P_ID { get; set; }
        public bool IsOnDuty { get; set; }
        public Nullable<int> InsertedBy { get; set; }
    
        public virtual Doctor_cu Doctor_cu { get; set; }
        public virtual DoctorCategory_cu DoctorCategory_cu { get; set; }
        public virtual Service_cu Service_cu { get; set; }
        public virtual ServiceCategory_cu ServiceCategory_cu { get; set; }
        public virtual ServiceType_p ServiceType_p { get; set; }
        public virtual User_cu User_cu { get; set; }
    }
}
