//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor_cu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctor_cu()
        {
            this.Doctor_Diagnosis_cu = new HashSet<Doctor_Diagnosis_cu>();
            this.Doctor_DiagnosisCategory_cu = new HashSet<Doctor_DiagnosisCategory_cu>();
            this.Doctor_Service_cu = new HashSet<Doctor_Service_cu>();
            this.Doctor_StationPointStage_cu = new HashSet<Doctor_StationPointStage_cu>();
            this.Doctor_Symptoms_cu = new HashSet<Doctor_Symptoms_cu>();
            this.Doctor_SymptomsCategory_cu = new HashSet<Doctor_SymptomsCategory_cu>();
            this.InvoiceDetails = new HashSet<InvoiceDetail>();
            this.VisitTimings = new HashSet<VisitTiming>();
            this.QueueManagers = new HashSet<QueueManager>();
        }
    
        public int Person_CU_ID { get; set; }
        public Nullable<int> DoctorSpecialization_P_ID { get; set; }
        public Nullable<int> DoctorCategory_CU_ID { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsInternal { get; set; }
        public Nullable<int> DoctorTaxType_CU_ID { get; set; }
        public Nullable<int> DoctorProfessionalFeesIssuingType_P_ID { get; set; }
        public string PrivateMobile { get; set; }
        public Nullable<int> InsertedBy { get; set; }
        public Nullable<int> DoctorRank_P_ID { get; set; }
        public string InternalCode { get; set; }
    
        public virtual DoctorCategory_cu DoctorCategory_cu { get; set; }
        public virtual DoctorProfessionalFeesIssuingType_p DoctorProfessionalFeesIssuingType_p { get; set; }
        public virtual DoctorRank_p DoctorRank_p { get; set; }
        public virtual DoctorSpecialization_p DoctorSpecialization_p { get; set; }
        public virtual DoctorTaxType_cu DoctorTaxType_cu { get; set; }
        public virtual Person_cu Person_cu { get; set; }
        public virtual User_cu User_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doctor_Diagnosis_cu> Doctor_Diagnosis_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doctor_DiagnosisCategory_cu> Doctor_DiagnosisCategory_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doctor_Service_cu> Doctor_Service_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doctor_StationPointStage_cu> Doctor_StationPointStage_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doctor_Symptoms_cu> Doctor_Symptoms_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doctor_SymptomsCategory_cu> Doctor_SymptomsCategory_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitTiming> VisitTimings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QueueManager> QueueManagers { get; set; }
    }
}
