//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor_Diagnosis_cu
    {
        public int ID { get; set; }
        public int Doctor_CU_ID { get; set; }
        public Nullable<int> Diagnosis_CU_ID { get; set; }
        public bool IsOnDuty { get; set; }
        public Nullable<int> InsertedBy { get; set; }
        public bool IsMerkInsertion { get; set; }
    
        public virtual Diagnosis_cu Diagnosis_cu { get; set; }
        public virtual Doctor_cu Doctor_cu { get; set; }
        public virtual User_cu User_cu { get; set; }
    }
}
