//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_cu
    {
        public int Person_CU_ID { get; set; }
        public Nullable<int> EmployeeType_CU_ID { get; set; }
        public string AbbreviationName { get; set; }
        public int MilitaryStatus_P_ID { get; set; }
        public string Email { get; set; }
        public int EmploymentDate_CU_ID { get; set; }
        public bool IsOnDuty { get; set; }
        public Nullable<System.DateTime> RetirementDate { get; set; }
        public Nullable<int> InsertedBy { get; set; }
    
        public virtual EmployeeType_cu EmployeeType_cu { get; set; }
        public virtual EmploymentDate_cu EmploymentDate_cu { get; set; }
        public virtual MilitaryStatus_p MilitaryStatus_p { get; set; }
        public virtual Person_cu Person_cu { get; set; }
        public virtual User_cu User_cu { get; set; }
    }
}
