//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialStatementElement_cu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FinancialStatementElement_cu()
        {
            this.ChartOfAccount_FinancialStatementElement_cu = new HashSet<ChartOfAccount_FinancialStatementElement_cu>();
            this.FinancialStatementElement_cu1 = new HashSet<FinancialStatementElement_cu>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ParentFinancialStatementElement_CU_ID { get; set; }
        public int FinancialStatementElement_P_ID { get; set; }
        public string Name_P { get; set; }
        public string Name_S { get; set; }
        public string Description { get; set; }
        public bool IsOnDuty { get; set; }
        public bool IsSumVisible { get; set; }
        public bool IncludeInFinancialStatement { get; set; }
        public Nullable<int> InsertedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChartOfAccount_FinancialStatementElement_cu> ChartOfAccount_FinancialStatementElement_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinancialStatementElement_cu> FinancialStatementElement_cu1 { get; set; }
        public virtual FinancialStatementElement_cu FinancialStatementElement_cu2 { get; set; }
        public virtual FinancialStatementElement_p FinancialStatementElement_p { get; set; }
        public virtual User_cu User_cu { get; set; }
    }
}
