//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinanceInvoiceDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FinanceInvoiceDetail()
        {
            this.FinanceInvoiceDetail1 = new HashSet<FinanceInvoiceDetail>();
        }
    
        public int ID { get; set; }
        public int FinanceInvoiceID { get; set; }
        public Nullable<int> ParentInvoiceDetailID { get; set; }
        public Nullable<int> InventoryHousing_CU_ID { get; set; }
        public Nullable<int> InventoryItem_CU_ID { get; set; }
        public Nullable<double> PricePerUnit { get; set; }
        public Nullable<int> UnitMeasurment_CU_ID { get; set; }
        public Nullable<double> Quantity { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<double> DiscountAmount { get; set; }
        public bool IsOnDuty { get; set; }
        public string Description { get; set; }
        public bool IsSurchargeApplied { get; set; }
        public Nullable<double> SurchargeAmount { get; set; }
        public Nullable<int> InsertedBy { get; set; }
    
        public virtual FinanceInvoice FinanceInvoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinanceInvoiceDetail> FinanceInvoiceDetail1 { get; set; }
        public virtual FinanceInvoiceDetail FinanceInvoiceDetail2 { get; set; }
        public virtual InventoryHousing_cu InventoryHousing_cu { get; set; }
        public virtual InventoryItem_cu InventoryItem_cu { get; set; }
        public virtual UnitMeasurment_cu UnitMeasurment_cu { get; set; }
    }
}
