//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinanceInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FinanceInvoice()
        {
            this.CustomerPaymentTransactions = new HashSet<CustomerPaymentTransaction>();
            this.FinanceInvoiceDetails = new HashSet<FinanceInvoiceDetail>();
            this.FinanceInvoicePayments = new HashSet<FinanceInvoicePayment>();
        }
    
        public int ID { get; set; }
        public int InvoiceType_P_ID { get; set; }
        public int InvoicePaymentType_P_ID { get; set; }
        public System.DateTime InvoiceCreationDate { get; set; }
        public Nullable<int> Customer_CU_ID { get; set; }
        public Nullable<int> Supplier_CU_ID { get; set; }
        public bool IsPrinted { get; set; }
        public string InvoiceSerial { get; set; }
        public Nullable<System.DateTime> PrintingDate { get; set; }
        public bool IsPaymentsEnough { get; set; }
        public string Description { get; set; }
        public bool IsOnDuty { get; set; }
        public Nullable<bool> IsFinanciallyReviewed { get; set; }
        public Nullable<bool> IsFinanciallyCompleted { get; set; }
        public bool IsCancelled { get; set; }
        public Nullable<int> CancelledBy { get; set; }
        public Nullable<System.DateTime> CancellationDate { get; set; }
        public Nullable<bool> IsSuspended { get; set; }
        public Nullable<int> InsertedBy { get; set; }
    
        public virtual Customer_cu Customer_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerPaymentTransaction> CustomerPaymentTransactions { get; set; }
        public virtual InvoicePaymentType_p InvoicePaymentType_p { get; set; }
        public virtual InvoiceType_p InvoiceType_p { get; set; }
        public virtual Supplier_cu Supplier_cu { get; set; }
        public virtual User_cu User_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinanceInvoiceDetail> FinanceInvoiceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinanceInvoicePayment> FinanceInvoicePayments { get; set; }
        public virtual FinanceInvoiceShare FinanceInvoiceShare { get; set; }
    }
}
