//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialInterval_Month_cu
    {
        public int ID { get; set; }
        public int FinancialInterval_CU_ID { get; set; }
        public int Month_P_ID { get; set; }
        public Nullable<int> InsertedBy { get; set; }
    
        public virtual FinancialInterval_cu FinancialInterval_cu { get; set; }
        public virtual Month_p Month_p { get; set; }
        public virtual User_cu User_cu { get; set; }
    }
}
