//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralChartOfAccountType_cu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GeneralChartOfAccountType_cu()
        {
            this.CashBoxInOutTransactions = new HashSet<CashBoxInOutTransaction>();
            this.CashBoxTransactionType_GeneralChartOfAccountType_cu = new HashSet<CashBoxTransactionType_GeneralChartOfAccountType_cu>();
            this.ChartOfAccount_GeneralChartOfAccountType_cu = new HashSet<ChartOfAccount_GeneralChartOfAccountType_cu>();
        }
    
        public int ID { get; set; }
        public string Name_P { get; set; }
        public string Name_S { get; set; }
        public int GeneralChartOfAccountType_P_ID { get; set; }
        public bool IsOnDuty { get; set; }
        public string Description { get; set; }
        public int InsertedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashBoxInOutTransaction> CashBoxInOutTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashBoxTransactionType_GeneralChartOfAccountType_cu> CashBoxTransactionType_GeneralChartOfAccountType_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChartOfAccount_GeneralChartOfAccountType_cu> ChartOfAccount_GeneralChartOfAccountType_cu { get; set; }
        public virtual GeneralChartOfAccountType_p GeneralChartOfAccountType_p { get; set; }
        public virtual User_cu User_cu { get; set; }
    }
}
