//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class InPatientRoomBed_cu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InPatientRoomBed_cu()
        {
            this.InPatientRoomBed_InPatientAdmissionPricingType_cu = new HashSet<InPatientRoomBed_InPatientAdmissionPricingType_cu>();
            this.InvoiceDetail_Accommodation = new HashSet<InvoiceDetail_Accommodation>();
        }
    
        public int ID { get; set; }
        public string Name_P { get; set; }
        public string Name_S { get; set; }
        public int InPatientRoom_CU_ID { get; set; }
        public int InPatientRoomBedStatus_P_ID { get; set; }
        public string InternalCode { get; set; }
        public string ShortName { get; set; }
        public bool IsOnDuty { get; set; }
        public string Description { get; set; }
        public Nullable<int> InsertedBy { get; set; }
    
        public virtual InPatientRoom_cu InPatientRoom_cu { get; set; }
        public virtual InPatientRoomBedStatus_p InPatientRoomBedStatus_p { get; set; }
        public virtual User_cu User_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InPatientRoomBed_InPatientAdmissionPricingType_cu> InPatientRoomBed_InPatientAdmissionPricingType_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceDetail_Accommodation> InvoiceDetail_Accommodation { get; set; }
    }
}
