//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuranceCarrier_InsuranceLevel_cu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InsuranceCarrier_InsuranceLevel_cu()
        {
            this.InPatientRoom_InPatientAdmissionPricingType_cu = new HashSet<InPatientRoom_InPatientAdmissionPricingType_cu>();
            this.InPatientRoomBed_InPatientAdmissionPricingType_cu = new HashSet<InPatientRoomBed_InPatientAdmissionPricingType_cu>();
            this.InPatientRoomClassification_InPatientAdmissionPricingType_cu = new HashSet<InPatientRoomClassification_InPatientAdmissionPricingType_cu>();
            this.Patient_cu = new HashSet<Patient_cu>();
            this.ServicePrice_cu = new HashSet<ServicePrice_cu>();
        }
    
        public int ID { get; set; }
        public int InsuranceCarrier_CU_ID { get; set; }
        public int InsuranceLevel_CU_ID { get; set; }
        public bool IsOnDuty { get; set; }
        public double InsurancePercentage { get; set; }
        public Nullable<double> PatientMaxAmount { get; set; }
        public Nullable<int> InsertedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InPatientRoom_InPatientAdmissionPricingType_cu> InPatientRoom_InPatientAdmissionPricingType_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InPatientRoomBed_InPatientAdmissionPricingType_cu> InPatientRoomBed_InPatientAdmissionPricingType_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InPatientRoomClassification_InPatientAdmissionPricingType_cu> InPatientRoomClassification_InPatientAdmissionPricingType_cu { get; set; }
        public virtual InsuranceCarrier_cu InsuranceCarrier_cu { get; set; }
        public virtual InsuranceLevel_cu InsuranceLevel_cu { get; set; }
        public virtual User_cu User_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patient_cu> Patient_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicePrice_cu> ServicePrice_cu { get; set; }
    }
}
