//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryItemPrice_cu
    {
        public int ID { get; set; }
        public int InventoryItem_CU_ID { get; set; }
        public int InventoryItem_UnitMeasurment_CU_ID { get; set; }
        public System.DateTime Date { get; set; }
        public double Price { get; set; }
        public Nullable<int> Customer_CU_ID { get; set; }
        public int PriceType_P_ID { get; set; }
        public Nullable<int> Supplier_CU_ID { get; set; }
        public bool IsOnDuty { get; set; }
        public Nullable<int> InsertedBy { get; set; }
    
        public virtual Customer_cu Customer_cu { get; set; }
        public virtual InventoryItem_cu InventoryItem_cu { get; set; }
        public virtual InventoryItem_UnitMeasurment_cu InventoryItem_UnitMeasurment_cu { get; set; }
        public virtual PriceType_p PriceType_p { get; set; }
        public virtual Supplier_cu Supplier_cu { get; set; }
        public virtual User_cu User_cu { get; set; }
    }
}
