//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryItem_Printing_cu
    {
        public int ID { get; set; }
        public int InventoryItem_CU_ID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> RawMaterial_CU_ID { get; set; }
        public double PrintingMaxTimeInMinutes { get; set; }
        public Nullable<double> AddedMinutes { get; set; }
        public double PrintingAverageUnitCostPrice { get; set; }
        public bool UseRealCost { get; set; }
        public Nullable<double> PrintingRealCostPrice { get; set; }
        public string Description { get; set; }
        public Nullable<int> InsertedBy { get; set; }
        public bool IsOnDuty { get; set; }
    
        public virtual InventoryItem_cu InventoryItem_cu { get; set; }
        public virtual RawMaterials_cu RawMaterials_cu { get; set; }
        public virtual User_cu User_cu { get; set; }
    }
}
