//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryItem_UnitMeasurment_cu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InventoryItem_UnitMeasurment_cu()
        {
            this.InventoryItemPrice_cu = new HashSet<InventoryItemPrice_cu>();
        }
    
        public int ID { get; set; }
        public int InventoryItem_CU_ID { get; set; }
        public int UnitMeasurment_CU_ID { get; set; }
        public bool IsOnDuty { get; set; }
        public Nullable<int> InsertedBy { get; set; }
        public Nullable<bool> IsInventoryTracking { get; set; }
    
        public virtual InventoryItem_cu InventoryItem_cu { get; set; }
        public virtual UnitMeasurment_cu UnitMeasurment_cu { get; set; }
        public virtual User_cu User_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryItemPrice_cu> InventoryItemPrice_cu { get; set; }
    }
}
