//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoicePayment_Check
    {
        public int InvoicePaymentID { get; set; }
        public int Bank_CU_ID { get; set; }
        public Nullable<int> BankAccoumt_CU_ID { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> ExchangeDate { get; set; }
        public string CheckNumber { get; set; }
        public string Description { get; set; }
        public Nullable<int> InsertedBy { get; set; }
    
        public virtual Bank_cu Bank_cu { get; set; }
        public virtual BankAccount_cu BankAccount_cu { get; set; }
        public virtual InvoicePayment InvoicePayment { get; set; }
        public virtual User_cu User_cu { get; set; }
    }
}
