//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceShare
    {
        public int InvoiceID { get; set; }
        public Nullable<double> TotalRequestedAmount { get; set; }
        public double TotalPatientShare { get; set; }
        public double TotalInsuranceShare { get; set; }
        public double TotalPayment { get; set; }
        public bool IsInsuranceApplied { get; set; }
        public Nullable<int> InsuranceCarrier_CU_ID { get; set; }
        public Nullable<int> InsuanceLevel_CU_ID { get; set; }
        public Nullable<double> InsurancePercentageApplied { get; set; }
        public Nullable<double> InsurancePatientMaxAmount { get; set; }
        public Nullable<double> InsuranceMaxAmount { get; set; }
        public bool IsSurchargeApplied { get; set; }
        public Nullable<bool> IsSurchargeDistributedToInsurancePercentage { get; set; }
        public Nullable<bool> IsSurchargeAppliedToInsuranceOnly { get; set; }
        public Nullable<bool> IsSurchargeAppliedToPatientOnly { get; set; }
        public Nullable<double> TotalSurchargeAccummulativePercentage { get; set; }
        public bool IsStampApplied { get; set; }
        public Nullable<bool> IsStampDistributedToInsurancePercentage { get; set; }
        public Nullable<bool> IsStampAppliedToPatientOnly { get; set; }
        public Nullable<bool> IsStampAppliedToInsuranceOnly { get; set; }
        public Nullable<double> TotalStampAmount { get; set; }
        public Nullable<int> InsertedBy { get; set; }
    
        public virtual InsuranceCarrier_cu InsuranceCarrier_cu { get; set; }
        public virtual InsuranceLevel_cu InsuranceLevel_cu { get; set; }
        public virtual Invoice Invoice { get; set; }
        public virtual User_cu User_cu { get; set; }
    }
}
