//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoicePayment
    {
        public int ID { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public Nullable<int> Patient_CU_ID { get; set; }
        public System.DateTime Date { get; set; }
        public double Amount { get; set; }
        public int PaymentType_P_ID { get; set; }
        public string PaymentSerial { get; set; }
        public bool IsOnDuty { get; set; }
        public string Description { get; set; }
        public Nullable<int> InsertedBy { get; set; }
        public bool IsRemainingReturned { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual InvoicePayment_Check InvoicePayment_Check { get; set; }
        public virtual Patient_cu Patient_cu { get; set; }
        public virtual PaymentType_p PaymentType_p { get; set; }
        public virtual User_cu User_cu { get; set; }
        public virtual InvoicePayment_Visa InvoicePayment_Visa { get; set; }
    }
}
