//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.InvoiceDetails = new HashSet<InvoiceDetail>();
            this.InvoiceDiscounts = new HashSet<InvoiceDiscount>();
            this.InvoicePayments = new HashSet<InvoicePayment>();
            this.InvoiceRequestedAmounts = new HashSet<InvoiceRequestedAmount>();
        }
    
        public int ID { get; set; }
        public int InvoiceType_P_ID { get; set; }
        public int InvoicePaymentType_P_ID { get; set; }
        public System.DateTime InvoiceCreationDate { get; set; }
        public int Patient_CU_ID { get; set; }
        public bool IsPrinted { get; set; }
        public string InvoiceSerial { get; set; }
        public Nullable<System.DateTime> PrintingDate { get; set; }
        public bool IsPaymentsEnough { get; set; }
        public string Description { get; set; }
        public bool IsOnDuty { get; set; }
        public Nullable<bool> IsFinanciallyReviewed { get; set; }
        public Nullable<bool> IsMedicallyDone { get; set; }
        public Nullable<bool> IsFinanciallyCompleted { get; set; }
        public bool IsCancelled { get; set; }
        public Nullable<int> CancelledBy { get; set; }
        public Nullable<System.DateTime> CancellationDate { get; set; }
        public Nullable<bool> IsSuspended { get; set; }
        public Nullable<int> InvoiceCostingStrategy_P_ID { get; set; }
        public Nullable<int> InsertedBy { get; set; }
    
        public virtual InvoiceCostingStrategy_p InvoiceCostingStrategy_p { get; set; }
        public virtual Patient_cu Patient_cu { get; set; }
        public virtual InvoicePaymentType_p InvoicePaymentType_p { get; set; }
        public virtual InvoiceType_p InvoiceType_p { get; set; }
        public virtual User_cu User_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceDiscount> InvoiceDiscounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoicePayment> InvoicePayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceRequestedAmount> InvoiceRequestedAmounts { get; set; }
        public virtual InvoiceShare InvoiceShare { get; set; }
    }
}
