//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location_cu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Location_cu()
        {
            this.Department_cu = new HashSet<Department_cu>();
            this.Floor_cu = new HashSet<Floor_cu>();
        }
    
        public int ID { get; set; }
        public string Name_P { get; set; }
        public string Name_S { get; set; }
        public int Organization_P_ID { get; set; }
        public Nullable<int> Country_CU_ID { get; set; }
        public Nullable<int> City_CU_ID { get; set; }
        public Nullable<int> Region_CU_ID { get; set; }
        public Nullable<int> Territory_CU_ID { get; set; }
        public bool IsOnDuty { get; set; }
        public string Description { get; set; }
        public Nullable<int> InsertedBy { get; set; }
        public string Address { get; set; }
        public string InternalCode { get; set; }
    
        public virtual City_cu City_cu { get; set; }
        public virtual Country_cu Country_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Department_cu> Department_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Floor_cu> Floor_cu { get; set; }
        public virtual Organization_p Organization_p { get; set; }
        public virtual Region_cu Region_cu { get; set; }
        public virtual Terriotry_cu Terriotry_cu { get; set; }
        public virtual User_cu User_cu { get; set; }
    }
}
