//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogAuditing
    {
        public int ID { get; set; }
        public int CommonTransactionType_P_ID { get; set; }
        public Nullable<int> User_CU_ID { get; set; }
        public System.DateTime Date { get; set; }
        public string EntityName { get; set; }
        public string CurrentValues { get; set; }
        public string OriginalValues { get; set; }
    }
}
