//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medication_Dose_cu
    {
        public int ID { get; set; }
        public int Medication_CU_ID { get; set; }
        public int Dose_CU_ID { get; set; }
        public bool IsOnDuty { get; set; }
        public int InsertedBy { get; set; }
        public string Description { get; set; }
    
        public virtual Dose_cu Dose_cu { get; set; }
        public virtual Medication_cu Medication_cu { get; set; }
        public virtual User_cu User_cu { get; set; }
    }
}
