//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationMachine_StationPoint_cu
    {
        public int ID { get; set; }
        public Nullable<int> OrganizationMachine_CU_ID { get; set; }
        public Nullable<int> StationPoint_CU_ID { get; set; }
        public bool IsOnDuty { get; set; }
        public Nullable<int> InsertedBy { get; set; }
    
        public virtual OrganizationMachine_cu OrganizationMachine_cu { get; set; }
        public virtual User_cu User_cu { get; set; }
        public virtual StationPoint_cu StationPoint_cu { get; set; }
    }
}
