//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationMachine_cu
    {
        public int ID { get; set; }
        public string Name_P { get; set; }
        public Nullable<int> StationPoint_CU_ID { get; set; }
        public Nullable<int> StationPointStage_CU_ID { get; set; }
        public int OrganizationID { get; set; }
        public bool IsOnDuty { get; set; }
        public string SkinName { get; set; }
        public string Color { get; set; }
        public Nullable<int> InsertedBy { get; set; }
    
        public virtual Organization_p Organization_p { get; set; }
        public virtual StationPoint_cu StationPoint_cu { get; set; }
        public virtual StationPointStage_cu StationPointStage_cu { get; set; }
        public virtual User_UserGroup_cu User_UserGroup_cu { get; set; }
    }
}
