//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientDepositeBalance
    {
        public int ID { get; set; }
        public int Patient_CU_ID { get; set; }
        public int Service_CU_ID { get; set; }
        public System.DateTime Date { get; set; }
        public double Blance { get; set; }
        public int Factor { get; set; }
        public bool IsOnDuty { get; set; }
        public int InsertedBy { get; set; }
    
        public virtual Patient_cu Patient_cu { get; set; }
        public virtual Service_cu Service_cu { get; set; }
        public virtual User_cu User_cu { get; set; }
    }
}
