//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientAttachment_cu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PatientAttachment_cu()
        {
            this.VisitTiming_Attachment = new HashSet<VisitTiming_Attachment>();
        }
    
        public int ID { get; set; }
        public int Patient_CU_ID { get; set; }
        public string ImageName { get; set; }
        public string ImagePath { get; set; }
        public int ImageType_P_ID { get; set; }
        public bool IsOnDuty { get; set; }
        public string Description { get; set; }
        public Nullable<int> InsertedBy { get; set; }
    
        public virtual ImageType_p ImageType_p { get; set; }
        public virtual Patient_cu Patient_cu { get; set; }
        public virtual User_cu User_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitTiming_Attachment> VisitTiming_Attachment { get; set; }
    }
}
