//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person_cu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person_cu()
        {
            this.Person_ChartOfAccount_cu = new HashSet<Person_ChartOfAccount_cu>();
            this.Person_IdentificationCardType_cu = new HashSet<Person_IdentificationCardType_cu>();
            this.Person_Phone_cu = new HashSet<Person_Phone_cu>();
        }
    
        public int ID { get; set; }
        public string FirstName_P { get; set; }
        public string SecondName_P { get; set; }
        public string ThirdName_P { get; set; }
        public string FourthName_P { get; set; }
        public string FirstName_S { get; set; }
        public string SecondName_S { get; set; }
        public string ThirdName_S { get; set; }
        public string FourthName_S { get; set; }
        public Nullable<int> PersonType_P_ID { get; set; }
        public Nullable<int> PersonTitle_P_ID { get; set; }
        public Nullable<int> Nationality_CU_ID { get; set; }
        public bool Gender { get; set; }
        public Nullable<int> MaritalStatus_P_ID { get; set; }
        public Nullable<int> Religion_P_ID { get; set; }
        public Nullable<int> CountryOfResidence_CU_ID { get; set; }
        public Nullable<int> CityOfResidence_CU_ID { get; set; }
        public Nullable<int> Region_CU_ID { get; set; }
        public string Address { get; set; }
        public string Mobile1 { get; set; }
        public string Mobile2 { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string EMail { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public bool IsOnDuty { get; set; }
        public string AdditionalContactInfo { get; set; }
        public Nullable<int> IdentificationCardType_P_ID { get; set; }
        public string IdentificationCardNumber { get; set; }
        public Nullable<System.DateTime> IdentificationCardIssuingDate { get; set; }
        public Nullable<System.DateTime> IdentificationCardExpirationDate { get; set; }
    
        public virtual City_cu City_cu { get; set; }
        public virtual Country_cu Country_cu { get; set; }
        public virtual Country_cu Country_cu1 { get; set; }
        public virtual Customer_cu Customer_cu { get; set; }
        public virtual Doctor_cu Doctor_cu { get; set; }
        public virtual Employee_cu Employee_cu { get; set; }
        public virtual IdentificationCardType_p IdentificationCardType_p { get; set; }
        public virtual MaritalStatus_p MaritalStatus_p { get; set; }
        public virtual Patient_cu Patient_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person_ChartOfAccount_cu> Person_ChartOfAccount_cu { get; set; }
        public virtual PersonTitle_p PersonTitle_p { get; set; }
        public virtual PersonType_p PersonType_p { get; set; }
        public virtual Region_cu Region_cu { get; set; }
        public virtual Religion_p Religion_p { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person_IdentificationCardType_cu> Person_IdentificationCardType_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person_Phone_cu> Person_Phone_cu { get; set; }
        public virtual Supplier_cu Supplier_cu { get; set; }
        public virtual User_cu User_cu { get; set; }
    }
}
