//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawMaterialTranasction
    {
        public int ID { get; set; }
        public int RawMaterialTransactionType_P_ID { get; set; }
        public int RawMaterial_CU_ID { get; set; }
        public Nullable<int> Color_CU_ID { get; set; }
        public int DividedByType_P_ID { get; set; }
        public int Count { get; set; }
        public double PuchasingPrice { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Height { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> InsertedBy { get; set; }
        public bool IsOnDuty { get; set; }
    
        public virtual Color_cu Color_cu { get; set; }
        public virtual DividedByType_p DividedByType_p { get; set; }
        public virtual RawMaterials_cu RawMaterials_cu { get; set; }
        public virtual RawMaterialTranasctionType_p RawMaterialTranasctionType_p { get; set; }
        public virtual User_cu User_cu { get; set; }
    }
}
