//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawMaterials_cu
    {
        public int ID { get; set; }
        public string Name_P { get; set; }
        public string Name_S { get; set; }
        public int RawTypeID { get; set; }
        public double Thickness { get; set; }
        public double Width { get; set; }
        public double Height { get; set; }
        public double Weight { get; set; }
        public System.DateTime PurchasingDate { get; set; }
        public double PurchasingPrice { get; set; }
        public Nullable<int> InsertedBy { get; set; }
        public bool IsOnDuty { get; set; }
    
        public virtual RawMaterialType_p RawMaterialType_p { get; set; }
        public virtual User_cu User_cu { get; set; }
    }
}
