//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_ChartOfAccount_cu
    {
        public int ID { get; set; }
        public int Service_CU_ID { get; set; }
        public int ChartOfAccount_CU_ID { get; set; }
        public bool IsOnDuty { get; set; }
        public int InsertedBy { get; set; }
    
        public virtual ChartOfAccount_cu ChartOfAccount_cu { get; set; }
    }
}
