//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicePrice_cu
    {
        public int ID { get; set; }
        public Nullable<int> Service_CU_ID { get; set; }
        public Nullable<int> ServiceCategory_CU_ID { get; set; }
        public Nullable<int> Doctor_CU_ID { get; set; }
        public Nullable<int> DoctorSpecialization_P_ID { get; set; }
        public Nullable<int> DoctorRank_P_ID { get; set; }
        public Nullable<int> DoctorCategory_CU_ID { get; set; }
        public double Price { get; set; }
        public Nullable<int> InsuranceCarrier_InsuranceLevel_CU_ID { get; set; }
        public Nullable<double> InsurancePrice { get; set; }
        public bool IsOnDuty { get; set; }
        public Nullable<int> InsertedBy { get; set; }
    
        public virtual DoctorCategory_cu DoctorCategory_cu { get; set; }
        public virtual DoctorRank_p DoctorRank_p { get; set; }
        public virtual DoctorSpecialization_p DoctorSpecialization_p { get; set; }
        public virtual InsuranceCarrier_InsuranceLevel_cu InsuranceCarrier_InsuranceLevel_cu { get; set; }
        public virtual Service_cu Service_cu { get; set; }
        public virtual ServiceCategory_cu ServiceCategory_cu { get; set; }
        public virtual User_cu User_cu { get; set; }
    }
}
