//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_cu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service_cu()
        {
            this.Doctor_Service_cu = new HashSet<Doctor_Service_cu>();
            this.InvoiceDetails = new HashSet<InvoiceDetail>();
            this.PatientDepositeBalances = new HashSet<PatientDepositeBalance>();
            this.QueueManagers = new HashSet<QueueManager>();
            this.Service_cu1 = new HashSet<Service_cu>();
            this.Service_StationPoint_cu = new HashSet<Service_StationPoint_cu>();
            this.Service_StationPointStage_cu = new HashSet<Service_StationPointStage_cu>();
            this.Service_Surcharge_cu = new HashSet<Service_Surcharge_cu>();
            this.ServicePrice_cu = new HashSet<ServicePrice_cu>();
            this.VisitTiming_InvestigationReservation = new HashSet<VisitTiming_InvestigationReservation>();
            this.VisitTiming_LabReservation = new HashSet<VisitTiming_LabReservation>();
            this.VisitTiming_SurgeryReservation = new HashSet<VisitTiming_SurgeryReservation>();
        }
    
        public int ID { get; set; }
        public string Name_P { get; set; }
        public string Name_S { get; set; }
        public Nullable<int> ServiceCategory_CU_ID { get; set; }
        public Nullable<int> ServiceType_P_ID { get; set; }
        public Nullable<int> ParentService_CU_ID { get; set; }
        public string InternalCode { get; set; }
        public bool IsOnDuty { get; set; }
        public Nullable<int> ChartOfAccount_CU_ID { get; set; }
        public Nullable<bool> EnforceCategorization { get; set; }
        public Nullable<bool> IsDailyCharged { get; set; }
        public Nullable<double> DefaultPrice { get; set; }
        public Nullable<bool> AllowAddmission { get; set; }
        public string Description { get; set; }
        public Nullable<int> InsertedBy { get; set; }
    
        public virtual ChartOfAccount_cu ChartOfAccount_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doctor_Service_cu> Doctor_Service_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientDepositeBalance> PatientDepositeBalances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QueueManager> QueueManagers { get; set; }
        public virtual ServiceCategory_cu ServiceCategory_cu { get; set; }
        public virtual ServiceType_p ServiceType_p { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service_cu> Service_cu1 { get; set; }
        public virtual Service_cu Service_cu2 { get; set; }
        public virtual User_cu User_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service_StationPoint_cu> Service_StationPoint_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service_StationPointStage_cu> Service_StationPointStage_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service_Surcharge_cu> Service_Surcharge_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicePrice_cu> ServicePrice_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitTiming_InvestigationReservation> VisitTiming_InvestigationReservation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitTiming_LabReservation> VisitTiming_LabReservation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitTiming_SurgeryReservation> VisitTiming_SurgeryReservation { get; set; }
    }
}
