//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_StationPointStage_cu
    {
        public int ID { get; set; }
        public int Service_CU_ID { get; set; }
        public int StationPointStage_CU_ID { get; set; }
        public bool IsOnDuty { get; set; }
        public Nullable<int> InsertedBy { get; set; }
    
        public virtual Service_cu Service_cu { get; set; }
        public virtual StationPointStage_cu StationPointStage_cu { get; set; }
        public virtual User_cu User_cu { get; set; }
    }
}
