//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Surcharge_cu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Surcharge_cu()
        {
            this.InvoiceType_Surcharge_cu = new HashSet<InvoiceType_Surcharge_cu>();
            this.Service_Surcharge_cu = new HashSet<Service_Surcharge_cu>();
            this.ServiceCategory_Surcharge_cu = new HashSet<ServiceCategory_Surcharge_cu>();
            this.ServiceType_Surcharge_cu = new HashSet<ServiceType_Surcharge_cu>();
        }
    
        public int ID { get; set; }
        public int SurchargeType_P_ID { get; set; }
        public string Name_P { get; set; }
        public string Name_S { get; set; }
        public bool IsPercentage { get; set; }
        public double Amount { get; set; }
        public bool IsOnDuty { get; set; }
        public string Description { get; set; }
        public Nullable<int> InsertedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceType_Surcharge_cu> InvoiceType_Surcharge_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service_Surcharge_cu> Service_Surcharge_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceCategory_Surcharge_cu> ServiceCategory_Surcharge_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceType_Surcharge_cu> ServiceType_Surcharge_cu { get; set; }
        public virtual User_cu User_cu { get; set; }
        public virtual SurchargeType_p SurchargeType_p { get; set; }
    }
}
