//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Symptoms_cu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Symptoms_cu()
        {
            this.Doctor_Symptoms_cu = new HashSet<Doctor_Symptoms_cu>();
            this.Symptoms_cu1 = new HashSet<Symptoms_cu>();
            this.SymptomsCategory_Symptoms_cu = new HashSet<SymptomsCategory_Symptoms_cu>();
            this.VisitTiming_Symptoms = new HashSet<VisitTiming_Symptoms>();
        }
    
        public int ID { get; set; }
        public string Name_P { get; set; }
        public string Name_S { get; set; }
        public Nullable<int> ParentSymptoms_CU_ID { get; set; }
        public bool IsDoctorRelated { get; set; }
        public string Description { get; set; }
        public string Abbreviation { get; set; }
        public bool IsOnDuty { get; set; }
        public Nullable<int> InsertedBy { get; set; }
        public bool IsMerkInsertion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doctor_Symptoms_cu> Doctor_Symptoms_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Symptoms_cu> Symptoms_cu1 { get; set; }
        public virtual Symptoms_cu Symptoms_cu2 { get; set; }
        public virtual User_cu User_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SymptomsCategory_Symptoms_cu> SymptomsCategory_Symptoms_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitTiming_Symptoms> VisitTiming_Symptoms { get; set; }
    }
}
