//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class SymptomsCategory_cu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SymptomsCategory_cu()
        {
            this.Doctor_SymptomsCategory_cu = new HashSet<Doctor_SymptomsCategory_cu>();
            this.SymptomsCategory_cu1 = new HashSet<SymptomsCategory_cu>();
            this.SymptomsCategory_Symptoms_cu = new HashSet<SymptomsCategory_Symptoms_cu>();
        }
    
        public int ID { get; set; }
        public string Name_P { get; set; }
        public string Name_S { get; set; }
        public Nullable<int> ParentSymptomsCategory_CU_ID { get; set; }
        public bool IsDoctorRelated { get; set; }
        public string Abbreviation { get; set; }
        public bool IsOnDuty { get; set; }
        public Nullable<int> InsertedBy { get; set; }
        public bool IsMerkInsertion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doctor_SymptomsCategory_cu> Doctor_SymptomsCategory_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SymptomsCategory_cu> SymptomsCategory_cu1 { get; set; }
        public virtual SymptomsCategory_cu SymptomsCategory_cu2 { get; set; }
        public virtual User_cu User_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SymptomsCategory_Symptoms_cu> SymptomsCategory_Symptoms_cu { get; set; }
    }
}
