//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToBeInserted_cu
    {
        public int ID { get; set; }
        public string Name_P { get; set; }
        public Nullable<int> VisitAssessmentTopic_P_ID { get; set; }
        public Nullable<int> InsertedBy { get; set; }
    
        public virtual User_cu User_cu { get; set; }
        public virtual VisitAssessmentTopic_p VisitAssessmentTopic_p { get; set; }
    }
}
