//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitMeasurmentTreeLink_cu
    {
        public int ID { get; set; }
        public int ParentUnitMeasurment_CU_ID { get; set; }
        public int ChildUnitMeasurment_CU_ID { get; set; }
        public double EncapsulatedChildQantity { get; set; }
        public bool IsOnDuty { get; set; }
        public Nullable<int> InsertedBy { get; set; }
    
        public virtual UnitMeasurment_cu UnitMeasurment_cu { get; set; }
        public virtual UnitMeasurment_cu UnitMeasurment_cu1 { get; set; }
        public virtual User_cu User_cu { get; set; }
    }
}
