//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Application_cu
    {
        public int ID { get; set; }
        public int User_CU_ID { get; set; }
        public int Application_P_ID { get; set; }
        public bool IsOnDuty { get; set; }
        public string Description { get; set; }
        public Nullable<int> InsertedBy { get; set; }
    
        public virtual Application_p Application_p { get; set; }
        public virtual User_cu User_cu { get; set; }
        public virtual User_cu User_cu1 { get; set; }
    }
}
