//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_cu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_cu()
        {
            this.AccountingJournalEntryTransactions = new HashSet<AccountingJournalEntryTransaction>();
            this.AccountingJournalTransactions = new HashSet<AccountingJournalTransaction>();
            this.ActiveSalaryEffect_cu = new HashSet<ActiveSalaryEffect_cu>();
            this.Address_cu = new HashSet<Address_cu>();
            this.AddressRefrenceType_cu = new HashSet<AddressRefrenceType_cu>();
            this.Bank_cu = new HashSet<Bank_cu>();
            this.BankAccount_cu = new HashSet<BankAccount_cu>();
            this.CashBox_cu = new HashSet<CashBox_cu>();
            this.CashBoxInOutTransactions = new HashSet<CashBoxInOutTransaction>();
            this.CashBoxInOutTransactions1 = new HashSet<CashBoxInOutTransaction>();
            this.CashBoxInOutTransaction_AccountingJournalTransaction = new HashSet<CashBoxInOutTransaction_AccountingJournalTransaction>();
            this.CashBoxTransactionType_GeneralChartOfAccountType_cu = new HashSet<CashBoxTransactionType_GeneralChartOfAccountType_cu>();
            this.ChartOfAccount_cu = new HashSet<ChartOfAccount_cu>();
            this.ChartOfAccount_FinancialStatementElement_cu = new HashSet<ChartOfAccount_FinancialStatementElement_cu>();
            this.ChartOfAccount_GeneralChartOfAccountType_cu = new HashSet<ChartOfAccount_GeneralChartOfAccountType_cu>();
            this.ChartOfAccountBalances = new HashSet<ChartOfAccountBalance>();
            this.City_cu = new HashSet<City_cu>();
            this.Country_cu = new HashSet<Country_cu>();
            this.Currency_cu = new HashSet<Currency_cu>();
            this.Customer_cu = new HashSet<Customer_cu>();
            this.CustomerPaymentTransactions = new HashSet<CustomerPaymentTransaction>();
            this.Department_cu = new HashSet<Department_cu>();
            this.Department_JobTitle_cu = new HashSet<Department_JobTitle_cu>();
            this.Department_JobTitle_WorkingShiftTitle_cu = new HashSet<Department_JobTitle_WorkingShiftTitle_cu>();
            this.Diagnosis_cu = new HashSet<Diagnosis_cu>();
            this.DiagnosisCategory_cu = new HashSet<DiagnosisCategory_cu>();
            this.DiagnosisCategory_Diagnosis_cu = new HashSet<DiagnosisCategory_Diagnosis_cu>();
            this.Doctor_cu = new HashSet<Doctor_cu>();
            this.Doctor_Diagnosis_cu = new HashSet<Doctor_Diagnosis_cu>();
            this.Doctor_DiagnosisCategory_cu = new HashSet<Doctor_DiagnosisCategory_cu>();
            this.Doctor_Service_cu = new HashSet<Doctor_Service_cu>();
            this.Doctor_Symptoms_cu = new HashSet<Doctor_Symptoms_cu>();
            this.Doctor_SymptomsCategory_cu = new HashSet<Doctor_SymptomsCategory_cu>();
            this.DoctorCategory_cu = new HashSet<DoctorCategory_cu>();
            this.DoctorFeesService_cu = new HashSet<DoctorFeesService_cu>();
            this.DoctorTaxType_cu = new HashSet<DoctorTaxType_cu>();
            this.Dose_cu = new HashSet<Dose_cu>();
            this.Employee_cu = new HashSet<Employee_cu>();
            this.Employee_Department_JobTitle_cu = new HashSet<Employee_Department_JobTitle_cu>();
            this.Employee_WorkingShift_cu = new HashSet<Employee_WorkingShift_cu>();
            this.Employee_WorkingShiftTitle_cu = new HashSet<Employee_WorkingShiftTitle_cu>();
            this.EmployeeType_cu = new HashSet<EmployeeType_cu>();
            this.EmploymentDate_cu = new HashSet<EmploymentDate_cu>();
            this.FinanceInvoices = new HashSet<FinanceInvoice>();
            this.FinanceInvoicePayments = new HashSet<FinanceInvoicePayment>();
            this.FinanceInvoiceShares = new HashSet<FinanceInvoiceShare>();
            this.FinancialInterval_cu = new HashSet<FinancialInterval_cu>();
            this.FinancialInterval_Month_cu = new HashSet<FinancialInterval_Month_cu>();
            this.FinancialStatementElement_cu = new HashSet<FinancialStatementElement_cu>();
            this.Floor_cu = new HashSet<Floor_cu>();
            this.GeneralChartOfAccountType_cu = new HashSet<GeneralChartOfAccountType_cu>();
            this.InPatientRoom_cu = new HashSet<InPatientRoom_cu>();
            this.InPatientRoom_InPatientAdmissionPricingType_cu = new HashSet<InPatientRoom_InPatientAdmissionPricingType_cu>();
            this.InPatientRoomBed_cu = new HashSet<InPatientRoomBed_cu>();
            this.InPatientRoomBed_InPatientAdmissionPricingType_cu = new HashSet<InPatientRoomBed_InPatientAdmissionPricingType_cu>();
            this.InPatientRoomClassification_cu = new HashSet<InPatientRoomClassification_cu>();
            this.InPatientRoomClassification_InPatientAdmissionPricingType_cu = new HashSet<InPatientRoomClassification_InPatientAdmissionPricingType_cu>();
            this.InsuranceCarrier_cu = new HashSet<InsuranceCarrier_cu>();
            this.InsuranceCarrier_InsuranceLevel_cu = new HashSet<InsuranceCarrier_InsuranceLevel_cu>();
            this.InsuranceLevel_cu = new HashSet<InsuranceLevel_cu>();
            this.InventoryHousing_cu = new HashSet<InventoryHousing_cu>();
            this.InventoryItem_cu = new HashSet<InventoryItem_cu>();
            this.InventoryItem_UnitMeasurment_cu = new HashSet<InventoryItem_UnitMeasurment_cu>();
            this.InventoryItemBrand_cu = new HashSet<InventoryItemBrand_cu>();
            this.InventoryItemCategory_cu = new HashSet<InventoryItemCategory_cu>();
            this.InventoryItemPrice_cu = new HashSet<InventoryItemPrice_cu>();
            this.InventoryItemTransactions = new HashSet<InventoryItemTransaction>();
            this.Invoices = new HashSet<Invoice>();
            this.InvoiceDetails = new HashSet<InvoiceDetail>();
            this.InvoiceDetail_Accommodation = new HashSet<InvoiceDetail_Accommodation>();
            this.InvoiceDetail_DoctorFees = new HashSet<InvoiceDetail_DoctorFees>();
            this.InvoiceDetail_Inventory = new HashSet<InvoiceDetail_Inventory>();
            this.InvoiceDiscounts = new HashSet<InvoiceDiscount>();
            this.InvoicePayments = new HashSet<InvoicePayment>();
            this.InvoicePayment_Check = new HashSet<InvoicePayment_Check>();
            this.InvoicePayment_Visa = new HashSet<InvoicePayment_Visa>();
            this.InvoiceRequestedAmounts = new HashSet<InvoiceRequestedAmount>();
            this.InvoiceShares = new HashSet<InvoiceShare>();
            this.InvoiceType_Surcharge_cu = new HashSet<InvoiceType_Surcharge_cu>();
            this.JobTitle_cu = new HashSet<JobTitle_cu>();
            this.Location_cu = new HashSet<Location_cu>();
            this.Manager_cu = new HashSet<Manager_cu>();
            this.MedicalStage_cu = new HashSet<MedicalStage_cu>();
            this.Medication_cu = new HashSet<Medication_cu>();
            this.Medication_Dose_cu = new HashSet<Medication_Dose_cu>();
            this.MedicationCategory_cu = new HashSet<MedicationCategory_cu>();
            this.Organization_p = new HashSet<Organization_p>();
            this.Patient_cu = new HashSet<Patient_cu>();
            this.PatientAttachment_cu = new HashSet<PatientAttachment_cu>();
            this.PatientDepositeBalances = new HashSet<PatientDepositeBalance>();
            this.PEM_ElementPrintOrder_cu = new HashSet<PEM_ElementPrintOrder_cu>();
            this.PEMRSavingMode_User_cu = new HashSet<PEMRSavingMode_User_cu>();
            this.PEMRSavingMode_User_cu1 = new HashSet<PEMRSavingMode_User_cu>();
            this.Person_ChartOfAccount_cu = new HashSet<Person_ChartOfAccount_cu>();
            this.Person_IdentificationCardType_cu = new HashSet<Person_IdentificationCardType_cu>();
            this.Person_Phone_cu = new HashSet<Person_Phone_cu>();
            this.PersonType_ChartOfAccount_cu = new HashSet<PersonType_ChartOfAccount_cu>();
            this.PupillaryAbnormalities_cu = new HashSet<PupillaryAbnormalities_cu>();
            this.PupillaryRAPDCauses_cu = new HashSet<PupillaryRAPDCauses_cu>();
            this.QueueManagers = new HashSet<QueueManager>();
            this.Region_cu = new HashSet<Region_cu>();
            this.RoleRegistration_cu = new HashSet<RoleRegistration_cu>();
            this.SegmentSign_cu = new HashSet<SegmentSign_cu>();
            this.SegmentSignCategory_cu = new HashSet<SegmentSignCategory_cu>();
            this.Service_cu = new HashSet<Service_cu>();
            this.Service_StationPoint_cu = new HashSet<Service_StationPoint_cu>();
            this.Service_Surcharge_cu = new HashSet<Service_Surcharge_cu>();
            this.ServiceCategory_cu = new HashSet<ServiceCategory_cu>();
            this.ServiceCategory_StationPoint_cu = new HashSet<ServiceCategory_StationPoint_cu>();
            this.ServiceCategory_Surcharge_cu = new HashSet<ServiceCategory_Surcharge_cu>();
            this.ServicePrice_cu = new HashSet<ServicePrice_cu>();
            this.ServiceType_ChartOfAccount_cu = new HashSet<ServiceType_ChartOfAccount_cu>();
            this.ServiceType_StationPoint_cu = new HashSet<ServiceType_StationPoint_cu>();
            this.ServiceType_Surcharge_cu = new HashSet<ServiceType_Surcharge_cu>();
            this.StationPoint_cu = new HashSet<StationPoint_cu>();
            this.StationPointStage_cu = new HashSet<StationPointStage_cu>();
            this.Supplier_cu = new HashSet<Supplier_cu>();
            this.Surcharge_cu = new HashSet<Surcharge_cu>();
            this.Symptoms_cu = new HashSet<Symptoms_cu>();
            this.SymptomsCategory_cu = new HashSet<SymptomsCategory_cu>();
            this.SymptomsCategory_Symptoms_cu = new HashSet<SymptomsCategory_Symptoms_cu>();
            this.Terriotry_cu = new HashSet<Terriotry_cu>();
            this.ToBeInserted_cu = new HashSet<ToBeInserted_cu>();
            this.TrialBalanceTransactions = new HashSet<TrialBalanceTransaction>();
            this.UnitMeasurment_cu = new HashSet<UnitMeasurment_cu>();
            this.UnitMeasurmentTreeLink_cu = new HashSet<UnitMeasurmentTreeLink_cu>();
            this.User_Application_cu = new HashSet<User_Application_cu>();
            this.User_Application_cu1 = new HashSet<User_Application_cu>();
            this.VisitTimings = new HashSet<VisitTiming>();
            this.User_UserGroup_cu = new HashSet<User_UserGroup_cu>();
            this.User_UserGroup_cu1 = new HashSet<User_UserGroup_cu>();
            this.UserGroup_Application_cu = new HashSet<UserGroup_Application_cu>();
            this.UserGroup_cu = new HashSet<UserGroup_cu>();
            this.VisitTiming_AdnexaSegmentSign = new HashSet<VisitTiming_AdnexaSegmentSign>();
            this.VisitTiming_AnteriorSegmentSign = new HashSet<VisitTiming_AnteriorSegmentSign>();
            this.VisitTiming_Attachment = new HashSet<VisitTiming_Attachment>();
            this.VisitTiming_EOMReading = new HashSet<VisitTiming_EOMReading>();
            this.VisitTiming_EOMSign = new HashSet<VisitTiming_EOMSign>();
            this.VisitTiming_InvestigationReservation = new HashSet<VisitTiming_InvestigationReservation>();
            this.VisitTiming_InvestigationResult = new HashSet<VisitTiming_InvestigationResult>();
            this.VisitTiming_LabReservation = new HashSet<VisitTiming_LabReservation>();
            this.VisitTiming_LabResult = new HashSet<VisitTiming_LabResult>();
            this.VisitTiming_MainAdnexaSegmentSign = new HashSet<VisitTiming_MainAdnexaSegmentSign>();
            this.VisitTiming_MainAnteriorSegmentSign = new HashSet<VisitTiming_MainAnteriorSegmentSign>();
            this.VisitTiming_MainEOMSign = new HashSet<VisitTiming_MainEOMSign>();
            this.VisitTiming_MainPosteriorSegmentSign = new HashSet<VisitTiming_MainPosteriorSegmentSign>();
            this.VisitTiming_Medication = new HashSet<VisitTiming_Medication>();
            this.VisitTiming_PosteriorSegmentSign = new HashSet<VisitTiming_PosteriorSegmentSign>();
            this.VisitTiming_Pupillary = new HashSet<VisitTiming_Pupillary>();
            this.VisitTiming_SocialHistory = new HashSet<VisitTiming_SocialHistory>();
            this.VisitTiming_SurgeryReservation = new HashSet<VisitTiming_SurgeryReservation>();
            this.VisitTiming_SurgeryResult = new HashSet<VisitTiming_SurgeryResult>();
            this.VisitTiming_TreatmentPlan = new HashSet<VisitTiming_TreatmentPlan>();
            this.VisitTiming_VisionRefractionReading = new HashSet<VisitTiming_VisionRefractionReading>();
            this.VisitTiming_VitalSign = new HashSet<VisitTiming_VitalSign>();
            this.WorkingShiftTitle_cu = new HashSet<WorkingShiftTitle_cu>();
        }
    
        public int Person_CU_ID { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public Nullable<int> OragnizationID { get; set; }
        public string InternalCode { get; set; }
        public string Description { get; set; }
        public Nullable<int> InsertedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountingJournalEntryTransaction> AccountingJournalEntryTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountingJournalTransaction> AccountingJournalTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActiveSalaryEffect_cu> ActiveSalaryEffect_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Address_cu> Address_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AddressRefrenceType_cu> AddressRefrenceType_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bank_cu> Bank_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BankAccount_cu> BankAccount_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashBox_cu> CashBox_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashBoxInOutTransaction> CashBoxInOutTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashBoxInOutTransaction> CashBoxInOutTransactions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashBoxInOutTransaction_AccountingJournalTransaction> CashBoxInOutTransaction_AccountingJournalTransaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashBoxTransactionType_GeneralChartOfAccountType_cu> CashBoxTransactionType_GeneralChartOfAccountType_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChartOfAccount_cu> ChartOfAccount_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChartOfAccount_FinancialStatementElement_cu> ChartOfAccount_FinancialStatementElement_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChartOfAccount_GeneralChartOfAccountType_cu> ChartOfAccount_GeneralChartOfAccountType_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChartOfAccountBalance> ChartOfAccountBalances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<City_cu> City_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Country_cu> Country_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Currency_cu> Currency_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer_cu> Customer_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerPaymentTransaction> CustomerPaymentTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Department_cu> Department_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Department_JobTitle_cu> Department_JobTitle_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Department_JobTitle_WorkingShiftTitle_cu> Department_JobTitle_WorkingShiftTitle_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Diagnosis_cu> Diagnosis_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiagnosisCategory_cu> DiagnosisCategory_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiagnosisCategory_Diagnosis_cu> DiagnosisCategory_Diagnosis_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doctor_cu> Doctor_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doctor_Diagnosis_cu> Doctor_Diagnosis_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doctor_DiagnosisCategory_cu> Doctor_DiagnosisCategory_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doctor_Service_cu> Doctor_Service_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doctor_Symptoms_cu> Doctor_Symptoms_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doctor_SymptomsCategory_cu> Doctor_SymptomsCategory_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorCategory_cu> DoctorCategory_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorFeesService_cu> DoctorFeesService_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorTaxType_cu> DoctorTaxType_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dose_cu> Dose_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_cu> Employee_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Department_JobTitle_cu> Employee_Department_JobTitle_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_WorkingShift_cu> Employee_WorkingShift_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_WorkingShiftTitle_cu> Employee_WorkingShiftTitle_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeType_cu> EmployeeType_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmploymentDate_cu> EmploymentDate_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinanceInvoice> FinanceInvoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinanceInvoicePayment> FinanceInvoicePayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinanceInvoiceShare> FinanceInvoiceShares { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinancialInterval_cu> FinancialInterval_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinancialInterval_Month_cu> FinancialInterval_Month_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinancialStatementElement_cu> FinancialStatementElement_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Floor_cu> Floor_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GeneralChartOfAccountType_cu> GeneralChartOfAccountType_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InPatientRoom_cu> InPatientRoom_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InPatientRoom_InPatientAdmissionPricingType_cu> InPatientRoom_InPatientAdmissionPricingType_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InPatientRoomBed_cu> InPatientRoomBed_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InPatientRoomBed_InPatientAdmissionPricingType_cu> InPatientRoomBed_InPatientAdmissionPricingType_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InPatientRoomClassification_cu> InPatientRoomClassification_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InPatientRoomClassification_InPatientAdmissionPricingType_cu> InPatientRoomClassification_InPatientAdmissionPricingType_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsuranceCarrier_cu> InsuranceCarrier_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsuranceCarrier_InsuranceLevel_cu> InsuranceCarrier_InsuranceLevel_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsuranceLevel_cu> InsuranceLevel_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryHousing_cu> InventoryHousing_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryItem_cu> InventoryItem_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryItem_UnitMeasurment_cu> InventoryItem_UnitMeasurment_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryItemBrand_cu> InventoryItemBrand_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryItemCategory_cu> InventoryItemCategory_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryItemPrice_cu> InventoryItemPrice_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryItemTransaction> InventoryItemTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceDetail_Accommodation> InvoiceDetail_Accommodation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceDetail_DoctorFees> InvoiceDetail_DoctorFees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceDetail_Inventory> InvoiceDetail_Inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceDiscount> InvoiceDiscounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoicePayment> InvoicePayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoicePayment_Check> InvoicePayment_Check { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoicePayment_Visa> InvoicePayment_Visa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceRequestedAmount> InvoiceRequestedAmounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceShare> InvoiceShares { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceType_Surcharge_cu> InvoiceType_Surcharge_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobTitle_cu> JobTitle_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Location_cu> Location_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Manager_cu> Manager_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalStage_cu> MedicalStage_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medication_cu> Medication_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medication_Dose_cu> Medication_Dose_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicationCategory_cu> MedicationCategory_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Organization_p> Organization_p { get; set; }
        public virtual Organization_p Organization_p1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patient_cu> Patient_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientAttachment_cu> PatientAttachment_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientDepositeBalance> PatientDepositeBalances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEM_ElementPrintOrder_cu> PEM_ElementPrintOrder_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEMRSavingMode_User_cu> PEMRSavingMode_User_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEMRSavingMode_User_cu> PEMRSavingMode_User_cu1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person_ChartOfAccount_cu> Person_ChartOfAccount_cu { get; set; }
        public virtual Person_cu Person_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person_IdentificationCardType_cu> Person_IdentificationCardType_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person_Phone_cu> Person_Phone_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonType_ChartOfAccount_cu> PersonType_ChartOfAccount_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PupillaryAbnormalities_cu> PupillaryAbnormalities_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PupillaryRAPDCauses_cu> PupillaryRAPDCauses_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QueueManager> QueueManagers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Region_cu> Region_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoleRegistration_cu> RoleRegistration_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SegmentSign_cu> SegmentSign_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SegmentSignCategory_cu> SegmentSignCategory_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service_cu> Service_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service_StationPoint_cu> Service_StationPoint_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service_Surcharge_cu> Service_Surcharge_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceCategory_cu> ServiceCategory_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceCategory_StationPoint_cu> ServiceCategory_StationPoint_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceCategory_Surcharge_cu> ServiceCategory_Surcharge_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicePrice_cu> ServicePrice_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceType_ChartOfAccount_cu> ServiceType_ChartOfAccount_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceType_StationPoint_cu> ServiceType_StationPoint_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceType_Surcharge_cu> ServiceType_Surcharge_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StationPoint_cu> StationPoint_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StationPointStage_cu> StationPointStage_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplier_cu> Supplier_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Surcharge_cu> Surcharge_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Symptoms_cu> Symptoms_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SymptomsCategory_cu> SymptomsCategory_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SymptomsCategory_Symptoms_cu> SymptomsCategory_Symptoms_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Terriotry_cu> Terriotry_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToBeInserted_cu> ToBeInserted_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrialBalanceTransaction> TrialBalanceTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnitMeasurment_cu> UnitMeasurment_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnitMeasurmentTreeLink_cu> UnitMeasurmentTreeLink_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Application_cu> User_Application_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Application_cu> User_Application_cu1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitTiming> VisitTimings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_UserGroup_cu> User_UserGroup_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_UserGroup_cu> User_UserGroup_cu1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserGroup_Application_cu> UserGroup_Application_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserGroup_cu> UserGroup_cu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitTiming_AdnexaSegmentSign> VisitTiming_AdnexaSegmentSign { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitTiming_AnteriorSegmentSign> VisitTiming_AnteriorSegmentSign { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitTiming_Attachment> VisitTiming_Attachment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitTiming_EOMReading> VisitTiming_EOMReading { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitTiming_EOMSign> VisitTiming_EOMSign { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitTiming_InvestigationReservation> VisitTiming_InvestigationReservation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitTiming_InvestigationResult> VisitTiming_InvestigationResult { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitTiming_LabReservation> VisitTiming_LabReservation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitTiming_LabResult> VisitTiming_LabResult { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitTiming_MainAdnexaSegmentSign> VisitTiming_MainAdnexaSegmentSign { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitTiming_MainAnteriorSegmentSign> VisitTiming_MainAnteriorSegmentSign { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitTiming_MainEOMSign> VisitTiming_MainEOMSign { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitTiming_MainPosteriorSegmentSign> VisitTiming_MainPosteriorSegmentSign { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitTiming_Medication> VisitTiming_Medication { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitTiming_PosteriorSegmentSign> VisitTiming_PosteriorSegmentSign { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitTiming_Pupillary> VisitTiming_Pupillary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitTiming_SocialHistory> VisitTiming_SocialHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitTiming_SurgeryReservation> VisitTiming_SurgeryReservation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitTiming_SurgeryResult> VisitTiming_SurgeryResult { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitTiming_TreatmentPlan> VisitTiming_TreatmentPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitTiming_VisionRefractionReading> VisitTiming_VisionRefractionReading { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitTiming_VitalSign> VisitTiming_VitalSign { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkingShiftTitle_cu> WorkingShiftTitle_cu { get; set; }
    }
}
