//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitTiming_SocialHistory
    {
        public int ID { get; set; }
        public int VisitTimingID { get; set; }
        public Nullable<bool> NegativeSocialHistory { get; set; }
        public Nullable<bool> DidYouEverSmoke { get; set; }
        public Nullable<double> NumberOfPacks { get; set; }
        public Nullable<double> NumberOfYears { get; set; }
        public string SmokeFurtherDetails { get; set; }
        public Nullable<bool> QuitingSmokeLessThan { get; set; }
        public Nullable<bool> QuitingSmokeBetween { get; set; }
        public Nullable<bool> QuitingSmokeMoreThan { get; set; }
        public string QuitingSmokeFurtherDetails { get; set; }
        public Nullable<bool> DrinkAlcohol { get; set; }
        public Nullable<double> HowMuchAlcohol { get; set; }
        public string AlcoholFurtherDetails { get; set; }
        public Nullable<bool> HadProblemWithAlcohol { get; set; }
        public Nullable<double> WhenHadProblemWIthAlcohol { get; set; }
        public string HadProblemWithAlcoholFurtherDetails { get; set; }
        public Nullable<bool> Addicted { get; set; }
        public string AddictionFurtherDetails { get; set; }
        public Nullable<bool> HadProblemWithAddiction { get; set; }
        public string HadProblemWithAddictionFurtherDetails { get; set; }
        public Nullable<bool> UseRecreationalDrugs { get; set; }
        public string UseRecreationalDrugsFurtherDetails { get; set; }
        public string GeneralDescription { get; set; }
        public bool IsOnDuty { get; set; }
        public Nullable<int> InsertedBy { get; set; }
    
        public virtual User_cu User_cu { get; set; }
        public virtual VisitTiming VisitTiming { get; set; }
    }
}
