//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitTiming_Symptoms
    {
        public int ID { get; set; }
        public int VisitTiming_MainSymptomsID { get; set; }
        public int Symptoms_CU_ID { get; set; }
        public bool IsOnDuty { get; set; }
        public Nullable<int> InsertedBy { get; set; }
    
        public virtual Symptoms_cu Symptoms_cu { get; set; }
        public virtual VisitTiming_MainSymptoms VisitTiming_MainSymptoms { get; set; }
    }
}
