//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitTiming_MedicalHistory
    {
        public int ID { get; set; }
        public int VisitTimingID { get; set; }
        public string FurtherDetails { get; set; }
        public Nullable<bool> HasDiabetes { get; set; }
        public Nullable<int> DiabetesType_P_ID { get; set; }
        public Nullable<bool> IsDiabetesControlled { get; set; }
        public Nullable<double> HbA1c { get; set; }
        public Nullable<int> DiabetesMedicationType_P_ID { get; set; }
        public Nullable<int> DiabetesMedication_CU_ID { get; set; }
        public Nullable<int> DiabetesDose_CU_ID { get; set; }
        public Nullable<int> DiabetesMedicationDuration { get; set; }
        public Nullable<int> DiabetesTimeDurationType_P_ID { get; set; }
        public Nullable<bool> IsHypertension { get; set; }
        public Nullable<bool> IsHypertensionControlled { get; set; }
        public Nullable<int> HypertensionMedication_CU_ID { get; set; }
        public Nullable<int> HypertensionDose_CU_ID { get; set; }
        public Nullable<int> HypertensionMedicationDuration { get; set; }
        public Nullable<int> HypertensionTimeDurationType_P_ID { get; set; }
        public Nullable<bool> IsDrugAllergy { get; set; }
        public Nullable<int> TriggerOfDrugAllergy_CU_ID { get; set; }
        public Nullable<bool> IsHepatitis { get; set; }
        public Nullable<bool> IsAsthma { get; set; }
        public bool IsOnDuty { get; set; }
        public Nullable<int> InsertedBy { get; set; }
    
        public virtual DiabetedMedicationType_p DiabetedMedicationType_p { get; set; }
        public virtual DiabetesType_p DiabetesType_p { get; set; }
        public virtual Dose_cu Dose_cu { get; set; }
        public virtual Dose_cu Dose_cu1 { get; set; }
        public virtual Medication_cu Medication_cu { get; set; }
        public virtual Medication_cu Medication_cu1 { get; set; }
        public virtual TimeDuration_p TimeDuration_p { get; set; }
        public virtual TimeDuration_p TimeDuration_p1 { get; set; }
        public virtual TriggerOfDrugAllergy_cu TriggerOfDrugAllergy_cu { get; set; }
        public virtual User_cu User_cu { get; set; }
        public virtual VisitTiming VisitTiming { get; set; }
    }
}
