//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitTiming_VitalSign
    {
        public int ID { get; set; }
        public int VisitTimingID { get; set; }
        public Nullable<System.DateTime> TakenDate { get; set; }
        public Nullable<System.DateTime> TakenTime { get; set; }
        public string GeneralDescription { get; set; }
        public Nullable<int> WeightUnit_P_ID { get; set; }
        public Nullable<double> WeightAmount { get; set; }
        public Nullable<int> HeightUnit_P_ID { get; set; }
        public Nullable<double> HeightAmount { get; set; }
        public string WeightDescription { get; set; }
        public Nullable<int> TemperatureUnit_P_ID { get; set; }
        public Nullable<double> TemperatureAmount { get; set; }
        public string TemperatureDescription { get; set; }
        public Nullable<double> BloodPressureAmountHigh { get; set; }
        public Nullable<double> BloodPressureAmountLow { get; set; }
        public Nullable<double> PulseAmount { get; set; }
        public Nullable<int> PulseReg { get; set; }
        public string BloodPressureDescription { get; set; }
        public Nullable<double> RespirationAmount { get; set; }
        public Nullable<double> OxygenAmount { get; set; }
        public Nullable<int> FIO2 { get; set; }
        public Nullable<double> SPO2Amount { get; set; }
        public string RespirationDescription { get; set; }
        public Nullable<bool> IsOnDuty { get; set; }
        public Nullable<int> InsertedBy { get; set; }
    
        public virtual HeightUnit_p HeightUnit_p { get; set; }
        public virtual TemperatureUnit_p TemperatureUnit_p { get; set; }
        public virtual User_cu User_cu { get; set; }
        public virtual VisitTiming VisitTiming { get; set; }
        public virtual WeightUnit_p WeightUnit_p { get; set; }
    }
}
