//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerkDataBaseBusinessLogicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitTiming_MainSymptoms
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VisitTiming_MainSymptoms()
        {
            this.VisitTiming_Symptoms = new HashSet<VisitTiming_Symptoms>();
        }
    
        public int ID { get; set; }
        public int VisitTimingID { get; set; }
        public string GeneralDescription { get; set; }
        public Nullable<int> PainLevel_P_ID { get; set; }
        public string PainLevelDescription { get; set; }
        public bool IsOnDuty { get; set; }
        public Nullable<int> InsertedBy { get; set; }
    
        public virtual PainLevel_p PainLevel_p { get; set; }
        public virtual VisitTiming VisitTiming { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitTiming_Symptoms> VisitTiming_Symptoms { get; set; }
    }
}
